#!/usr/bin/env bash
# Generate sitemap.xml from sitemap-pages.yaml.
#
# Usage (from project root):
#   src/build-sitemap.sh
#
# lastmod is taken from git (last commit touching that file) when available,
# otherwise today's date (UTC).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CONFIG_FILE="${PROJECT_ROOT}/sitemap-pages.yaml"
OUTPUT_FILE="${PROJECT_ROOT}/sitemap.xml"

if [[ ! -f "${CONFIG_FILE}" ]]; then
  echo "Error: config not found: ${CONFIG_FILE}" >&2
  exit 1
fi

if ! command -v yq >/dev/null 2>&1; then
  echo "Error: yq is required to parse sitemap-pages.yaml" >&2
  echo "Install with: brew install yq (macOS) or see https://github.com/mikefarah/yq" >&2
  exit 1
fi

lastmod_for() {
  local path="$1"
  local full="${PROJECT_ROOT}/${path}"
  local date=""

  if [[ -f "${full}" ]] && command -v git >/dev/null 2>&1; then
    date="$(git -C "${PROJECT_ROOT}" log -1 --format=%cs -- "${path}" 2>/dev/null || true)"
  fi

  if [[ -z "${date}" ]]; then
    date="$(date -u +%Y-%m-%d)"
  fi

  printf '%s' "${date}"
}

base_url="$(yq eval '.base_url' "${CONFIG_FILE}" | sed 's:/*$::')"
page_count="$(yq eval '.pages | length' "${CONFIG_FILE}")"

{
  cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by src/build-sitemap.sh from sitemap-pages.yaml — do not edit by hand -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
EOF

  for ((i = 0; i < page_count; i++)); do
    path="$(yq eval ".pages[$i].path" "${CONFIG_FILE}")"
    [[ -z "${path}" || "${path}" == "null" ]] && continue

    changefreq="$(yq eval ".pages[$i].changefreq // \"monthly\"" "${CONFIG_FILE}")"
    priority="$(yq eval ".pages[$i].priority // 0.5" "${CONFIG_FILE}")"
    lastmod="$(lastmod_for "${path}")"

    cat <<EOF
  <url>
    <loc>${base_url}/${path}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>
EOF
  done

  cat <<EOF
</urlset>
EOF
} > "${OUTPUT_FILE}"

echo "Wrote ${OUTPUT_FILE} (${page_count} page(s))"
