#!/bin/bash
while read oldrev newrev ref
do
if [[ $ref =~ .*/main$ ]];
then
echo "Main ref received.  Deploying main branch to production..."
git --work-tree=/usr/share/nginx/html --git-dir=$HOME/proj checkout -f
cp /usr/share/nginx/html/srkw-call-catalogue-files/call-catalog.yaml /usr/share/nginx/html/resources_config/call-catalog.yaml
python3 /usr/share/nginx/html/code/read_files.py /usr/share/nginx/html/resources_config/call-catalog.yaml /usr/share/nginx/html/resources_config/call-catalog
else
echo "Ref $ref successfully received.  Doing nothing: only the main branch may be deployed on this server."
fi
done
