name: Deploy on push

on:
  push:
     # Sequence of patterns matched against refs/heads
     branches:    
       - main
       - develop
       - front-end
       - actions-patch-1
jobs:
  get_pushed_branch:
    name: Get relevant branch
    runs-on: ubuntu-latest
    outputs:
      branch-name: ${{ steps.set-name.outputs.ref_branch }}
    steps:
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Get Ref brach name
        id: set-name
        run: |
          echo "${{ steps.branch-name.outputs.ref_branch }}"
          echo "::set-output name=ref_branch::${{ steps.branch-name.outputs.ref_branch }}"
        #  The branch that triggered the workflow run. e.g 1/merge, main
      
  deploy:
    name: Deploy
    # dependent jobs
    needs: get_pushed_branch 
    if: "always()&&(needs.get_pushed_branch.outputs.branch-name != null)" 
    uses: ./.github/workflows/manual_deploy.yml
    with:
      #branch: ${{ steps.branch-name.outputs.ref_branch }}
      branch: "${{ needs.get_pushed_branch.outputs.branch-name }}"
      #token: ${{ secrets.token }}
    secrets: inherit
  
  see-outputs:
    name: See outputs
    runs-on: ubuntu-latest
    needs: get_pushed_branch 
    # if: "always()&&(needs.get_pushed_branch.outputs.branch-name != null)" 
    steps:
      - name: See
        run: |
          echo "${{ needs.get_pushed_branch.outputs.branch-name }}"
